import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import AuthProvider from '@/components/AuthProvider/AuthProvider'
import NavBar from '@/components/Navbar/NavBar'
import Footer from '@/components/Footer/Footer'
import { ThemeProvider } from '@/context/ThemeContext'

const inter = Poppins({ subsets: ['latin'], weight: ['100', '500', '800'] })

export const metadata: Metadata = {
  title: 'Blog-auth | home',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ThemeProvider>
          <AuthProvider>
            <NavBar />
            <div className='container'>
              {children}
              <Footer />
            </div>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
