import ParticlesComponent from '@/utils/particles'
import { Metadata } from 'next'

interface Props {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: 'Blog-auth | auth',
  description: 'Generated by create next app'
}

export default function layout({ children }: Props) {
  return (
    <div>
      <ParticlesComponent />
      {children}
    </div>
  )
}
